version: "3.9"

services:
  planka:
    image: ghcr.io/nakkiibrks/planka:latest
    restart: on-failure
    volumes:
      - favicons:/app/public/favicons
      - user-avatars:/app/public/user-avatars
      - background-images:/app/public/background-images
      - attachments:/app/private/attachments
    ports:
      - 1337:1337
    environment:
      - BASE_URL=https://alfredohub.tech
      - DEFAULT_ADMIN_EMAIL=root@root.com
      - DEFAULT_ADMIN_USERNAME=root
      - DEFAULT_ADMIN_PASSWORD=J22B&qYb9pC09!
      - DEFAULT_ADMIN_NAME=root
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      plankanet:
        ipv4_address: 172.28.0.10

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      plankanet:
        ipv4_address: 172.28.0.11

volumes:
  favicons:
  user-avatars:
  background-images:
  attachments:
  db-data:

networks:
  plankanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
